### PR TITLE
Rework fetcher2/repo

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by rshym** [comment]
@andr2000 @arminn @iusyk could you please review?

**Comment by rshym** [comment]
Tested by successful build of full image of prod-devel doma.

**Comment by rshym** [comment]
Build of full image means that same repo fetcher was used to fetch DomA sources (with custom parameters), and  Dom0/DomD (with default behaviour).

**Comment by rshym** [comment]
Tested by successful build of full image of prod-aos with `xt-image` and `xt-update` targets. No issues were observed.

**Comment by rshym** [comment]
@andr2000 @iusyk @lorc  @arminn 
Could you please review?

**Comment by lorc** [comment]
Nitpicking:

`s/he or she/they`

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
"he or she" was changed to "they", according to comment.
Reviewer was added.

**Comment by rshym** [comment]
@iusyk could you please merge?

**Comment by rshym** [comment]
@iusyk could you please merge?

**Review by arminn — APPROVED** [review]

**Comment by rshym** [comment]
@iusyk could you please merge?

**Pull request merged**
